name: Build & Deploy (Hourly Evidence)

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 * * * *"   # every hour UTC
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build (evidence + archives)
        run: |
          python app.py --query "longevity therapy OR chronic disease treatment evidence" > build.log 2>&1 || true
          tail -n 200 build.log || true

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          force_orphan: true
