name: Deploy Blog to GitHub Pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"   # optional: rebuild daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install -r requirements.txt || true

      - name: Run generator
        run: python app.py

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
