name: Build and Deploy Site

on:                       # <-- this is the section
  push:
    branches: [ "main" ]
  workflow_dispatch:      # allows manual run from GitHub UI
  schedule:               # <-- you paste here
    - cron: "0 0 * * *"   # every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run app.py to generate site
        run: python app.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
