name: Run Agent Loop

on:
  workflow_dispatch:   # run manually
  schedule:
    - cron: "0 * * * *"   # every hour

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run agent loop
        run: python app.py

      - name: Commit results
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add results.json
          git commit -m "Update results [skip ci]" || echo "No changes to commit"
          git push
